# Generated by Django 3.2 on 2022-11-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20221106_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='label',
            field=models.ImageField(blank=True, upload_to='collections_labels/', verbose_name='Обложка'),
        ),
    ]
