# Generated by Django 3.2 on 2022-11-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_collection_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='tile_images/', verbose_name='Слайд')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.collection')),
            ],
        ),
    ]
